name: flutter_mvvm_example
description: Flutter MVVM example project.

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^0.1.2
  scoped_model: ^0.3.0
  font_awesome_flutter: ^8.0.1
  http: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.0.0

flutter:

  uses-material-design: true 

  fonts:
    - family: Distant Galaxy
      fonts:
        - asset: fonts/DISTGRG_.ttf
